### ISSUE TITLE
Support for PHP 7

### ISSUE THREAD

**Issue by FernandoNunes** [Reconix/Flexi-Auth-CI3#4]
I'm testing out your fork to CI 3 and i've encountered an issue that is due to PHP7 not allowing manually set salts:

A PHP Error was encountered
Severity: 8192
Message: password_hash(): Use of the 'salt' option to password_hash is deprecated
Filename: models/Flexi_auth_model.php
Line Number: 87

For now I just replaced $data with an empty array on password set and on password validation used the password_verify($verify_password, $database_password), other than that what I've tested seems fine with minor tweaks.

Keep up the good work.

**Comment by Reconix** [comment]
Personally I think it's the best Auth to get started with in Codeigniter, certainly helped me out a lot and hope it helps others. Haseydesign done a nice job.

If you have any improvements or fixes feel free to add them.

**Comment by Reconix** [comment]
Now working thanks to a friendly contribution by eafarooqi
